### ISSUE TITLE
Loop / Permanent Restart

### ISSUE THREAD

**Issue by joerg-rade** [fuiny/binarydoc-docker#4]
Hi,

thanks for providing binarydoc!

When I execute rebuild.sh (git bash under windows 10), I see the following in the console of fuiny/binarydoc:latest:
```
spawn mysql_config_editor set --login-path=binarydocjvm --host=binarydoc-db --user=root --password
Enter password:
spawn mysql_config_editor set --login-path=binarydocjvmadm --host=binarydoc-db --user=root --password
Enter password:
Thu Mar 25 15:27:23 UTC 2021 Waiting for DB to be Ready ...
[...]
Thu Mar 25 15:28:02 UTC 2021 DB Server is NOT ready yet
mysqld is alive
Thu Mar 25 15:28:03 UTC 2021 DB Server is ready now
Thu Mar 25 15:28:06 UTC 2021 Create DB Users if not exist
host user authentication_string
% fuinyadmin *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
% fuinyweb *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
% root *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
localhost mysql.infoschema $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED
localhost mysql.session $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED
localhost mysql.sys $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED
localhost root *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
Thu Mar 25 15:28:06 UTC 2021 Create DB Schema for Admin if not exists
ERROR 1418 (HY000) at line 206: This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
spawn mysql_config_editor set --login-path=binarydocjvm --host=binarydoc-db --user=root --password
Enter password:
spawn mysql_config_editor set --login-path=binarydocjvmadm --host=binarydoc-db --user=root --password
Enter password:
Thu Mar 25 15:28:08 UTC 2021 Waiting for DB to be Ready ...
mysqld is alive
Thu Mar 25 15:28:08 UTC 2021 DB Server is ready now
Thu Mar 25 15:28:11 UTC 2021 Create DB Users if not exist
host user authentication_string
% fuinyadmin *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
% fuinyweb *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
% root *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
localhost mysql.infoschema $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED
localhost mysql.session $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED
localhost mysql.sys $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED
localhost root *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
Thu Mar 25 15:28:12 UTC 2021 Create DB Schema for Admin if not exists
ERROR 1418 (HY000) at line 206: This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
[...]
```
docker version shows:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Am I doing something wrong?

Thanks in advance
Jörg

**Comment by fuinyroot** [comment]
Hi Jörg,

#### Root Cause Analysis

The error `ERROR 1418 (HY000) at line 206: This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)` should have been fixed by https://github.com/fuiny/binarydoc-docker/blob/master/etc/mysql/conf.d/mysql.cnf#L89 on MySQL `8`

* etc/mysql/conf.d/mysql.cnf#L89
```
# https://stackoverflow.com/questions/26015160/
log_bin_trust_function_creators = 1
```

If not, my best guess for now could be the config mapping at https://github.com/fuiny/binarydoc-docker/blob/master/docker-compose.yml#L22 is not working on Windows docker ? so the `mysql.cnf` may not take effect right now.

* docker-compose.yml#L22
```
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
```

To validate this guess, what you may try is:
* Make sure the MySQL docker is already running
* Open the url in browser http://127.0.0.1:10190/ and login as
  * Server: `binarydoc-db`
  * Username: `root`
  * Password: `123456`, or the password you set in `.env` file
* Click the link `Variables` at the top right
* Validate `log_bin_trust_function_creators` is `ON` or `OFF`
  * We expect it should be `ON` - which means the  `mysql.cnf#L89` take effect
  * If it is `OFF`, it means its a mapping issue at `docker-compose.yml#L22` and `mysql.cnf#L89` did not take effect

We will try to find a Windows Server to test it (to be honest we need to buy a windows license first since the current testing is on Linux right now)


#### Other Way Out

Well you don't have to run `rebuild.sh` to rebuild the docker images, it has been built at https://hub.docker.com/r/fuiny/binarydoc . The script `rebuild.sh` is designed for the local Dev/QA Linux machines.

So all you need to do is pull the image and run it:
* `docker-compose up -d`

**Comment by joerg-rade** [comment]
Hi there & thanks for the fast response!

•	Validate log_bin_trust_function_creators is OFF

-j

**Comment by fuinyroot** [comment]
HI @joerg-rade 

Thanks for the feedback, so it means the `docker-compose.yml#L22` mapping is not taking effect for `MySQL 8`  Windows Docker image. 

```
    ./etc/mysql/conf.d:/etc/mysql/conf.d
```

We will investigate a more reliable method to map the `mysql.cnf` into MySQL 8 docker.

**Comment by joerg-rade** [comment]
Appears to have been a case of PEBKAC ...

my Docker Desktop for Windows setup was not correct. I had to 
* uncheck Settings -> General -> Use WSL 2 based engine (which enabled Settings -> Resources ->  File Sharing) and 
* grant access to the FS with Settings -> Resources ->  File Sharing 

Thanks for your sopport!
